name: CI
on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  compat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        giz: [ 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0 ]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-giz@v2
      with:
        version: ${{ matrix.giz }}

    - name: Check compatibility with old Zig compilers
      run: ci/compat.sh
